### ISSUE TITLE
Related publications from CKAN 

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/ckanext-odm_library#47]
"Related publications", on "Access to public services" profile page of ODC site, were not linked from ODC's publication on CKAN. I found one of those Related publications is taken from ODMekong, and others 4 publications are not found on CKAN. 
![related publication](https://cloud.githubusercontent.com/assets/19201022/19724051/6aeb87aa-9ba8-11e6-842b-3b6f0fe49794.png)

**Comment by acorbi** [comment]
@vatana92 since I have just implemented https://github.com/OpenDevelopmentMekong/wpckan/issues/186, now it is possible to specify a **filter by organization** on the WPCKAN query by post's category under **Appearance > Widgets > Profile area bottom left**.

![screenshot from 2016-10-26 17-33-07](https://cloud.githubusercontent.com/assets/384894/19732800/48871252-9ba2-11e6-9d1f-31994c6af8ef.png)

Please adapt the corresponding widgets

> and others 4 publications are not found on CKAN. 

Why do you say they are not found, please follow the links:
- https://opendevelopmentcambodia.net/dataset/?id=the-socioeconomic-implications-of-population-aging-in-the-people-s-republic-of-china
- https://opendevelopmentcambodia.net/dataset/?id=the-availability-of-mental-health-and-psychosocial
- https://opendevelopmentcambodia.net/dataset/?id=re-integration-perspectives-of-victim-service
- https://opendevelopmentcambodia.net/dataset/?id=sector-assessment-summary-transport-myanmar-draft

and their equivalents in CKAN:
- https://data.opendevelopmentmekong.net/dataset/the-socioeconomic-implications-of-population-aging-in-the-people-s-republic-of-china
- https://data.opendevelopmentmekong.net/dataset/the-availability-of-mental-health-and-psychosocial
- https://data.opendevelopmentmekong.net/dataset/re-integration-perspectives-of-victim-service
- https://data.opendevelopmentmekong.net/dataset/sector-assessment-summary-transport-myanmar-draft

All of them resolve to a valid dataset.

im closing this issue, please re-open if reappears...

**Comment by vatana92** [comment]
I agree that those data are on CKAN, but when I search those by copying its title and paste in "Search", the result is "No dataset found".
![screenshot_1](https://cloud.githubusercontent.com/assets/19201022/19752186/a6150824-9c25-11e6-9b5a-c84848587d01.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/19201022/19752201/bb8c7d04-9c25-11e6-9bf3-1250f5709406.png)
